# Generated by Django 4.2b1 on 2023-04-04 10:45

import board.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('link', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('poster', models.CharField(blank=True, max_length=35)),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.UUIDField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bump', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='board.post')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=board.utils.path_for_image)),
                ('thumb', models.ImageField(upload_to=board.utils.path_for_thumb)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.post')),
            ],
        ),
    ]
