# Generated by Django 4.2 on 2023-06-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_user_global_janny'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
