# Generated by Django 4.1.4 on 2022-12-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(blank=True, max_length=35)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d/')),
                ('thumb', models.ImageField(blank=True, upload_to='post/thumbs/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, upload_to='post/videos/%Y/%m/%d/')),
                ('videothumb', models.ImageField(blank=True, upload_to='post/thumbs/%Y/%m/%d/')),
                ('bump', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeyapp.board')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journeyapp.post')),
            ],
        ),
    ]
