# Generated by Django 4.1.5 on 2023-02-17 19:23

from django.db import migrations, models
import django.db.models.deletion
import journeyapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('journeyapp', '0004_remove_post_image_remove_post_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=journeyapp.models.path_for_image)),
                ('thumb', models.ImageField(upload_to=journeyapp.models.path_for_thumb)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeyapp.post')),
            ],
        ),
    ]
