# Generated by Django 4.1.5 on 2023-02-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeyapp', '0005_remove_post_file_remove_post_thumb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journeyapp.post'),
        ),
    ]
